version: "3.8"

services:

  # the rust server image
  server:
    image: didstopia/rust-server:latest
    deploy: 
      resources:
        limits: 
          cpus: 3
          memory: 7144M
    volumes:
      - ./steamcmd/rust:/steamcmd/rust
    environment:
      # +nav_disable true - to speed up loading of server but disables animal movement and attacking
      RUST_SERVER_STARTUP_ARGUMENTS: '-batchmode -load -nographics +server.secure 1 +server.ip 0.0.0.0'
      RUST_SERVER_IDENTITY: 'lockhinator'
      # RUST_SERVER_PORT: '28015'
      RUST_SERVER_SEED: $SERVER_SEED
      RUST_SERVER_WORLDSIZE: 4500
      RUST_SERVER_NAME: "LOCKHINATOR.COM|US EAST|NEWB FRIENDLY"
      RUST_SERVER_MAXPLAYERS: 50
      RUST_SERVER_DESCRIPTION: Newb friendly rust server. No rules. Solos, Duos, Trios welcome.
      RUST_SERVER_URL: "lockhinator.com/rust"
      RUST_SERVER_BANNER_URL: "lockhinator.com/rust/server.png"
      RUST_SERVER_SAVE_INTERVAL: 600
      RUST_RCON_WEB: 1
      RUST_RCON_PORT: 28017
      RUST_RCON_PASSWORD: "${RCON_PASSWORD}"
      RUST_APP_PORT: 28082
      # - RUST_BRANCH 
      RUST_UPDATE_CHECKING: 1
      RUST_UPDATE_BRANCH: public
      RUST_START_MODE: 0
      RUST_OXIDE_ENABLED: 1
      RUST_OXIDE_UPDATE_ON_BOOT: 1
      RUST_RCON_SECURE_WEBSOCKET: 0
    ports:
      - 28015:28015
      - 28016:28016
      - 28017:28017
      - 28082:28082

