version: "3.8"

services:

  # the rust server image
  server:
    image: didstopia/rust-server:latest
    deploy: 
      resources:
        limits: 
          cpus: 3
          memory: 7144M
    volumes:
      - ./steamcmd/rust:/steamcmd/rust
    env_file:
      - ./.env
    ports:
      - 28015:28015
      - 28015:28015/udp
      - 28016:28016
      - 28082:28082
      - 8080:8080

